const path = require("path")
// console.log("user" + path.sep + "newFolder")
// console.log(path.delimiter)
// console.log(path.basename("/user/ali/index.js", ".js"))
// console.log(path.dirname("/user/ali/index.js"))
// console.log(path.extname("/user/ali/index.js"))
// console.log(path.join(path.sep ,"user", "ali", "tutorials", "frontEnd", "index.js"))
// console.log(path.isAbsolute(path.join(path.sep ,"user", "ali", "tutorials", "frontEnd", "index.js")))
// console.log(path.parse("/user/ali/index.js`"))
console.log(path.normalize("\\user/ali//someFolder\\index.js"))
console.log(__dirname)
console.log(__filename)
